// <auto-generated />
using System;
using LMSweb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMSweb.Migrations
{
    [DbContext(typeof(LMSContext))]
    [Migration("20230803015615_add_HasData")]
    partial class add_HasData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMSweb.Models.Answer", b =>
                {
                    b.Property<string>("Aid")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("AID");

                    b.Property<string>("Acontent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Atime")
                        .HasColumnType("datetime")
                        .HasColumnName("ATime");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("QuestionID");

                    b.HasKey("Aid");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("LMSweb.Models.Course", b =>
                {
                    b.Property<string>("Cid")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("CID");

                    b.Property<string>("Cname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("CName");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("TeacherId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("TeacherID");

                    b.Property<int>("TestType")
                        .HasMaxLength(128)
                        .HasColumnType("int");

                    b.HasKey("Cid");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("LMSweb.Models.Execution", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GroupID");

                    b.Property<string>("MissionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("MissionID");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId", "MissionId");

                    b.HasIndex("MissionId");

                    b.ToTable("Executions");
                });

            modelBuilder.Entity("LMSweb.Models.ExperimentalProcedure", b =>
                {
                    b.Property<string>("EprocedureId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("EProcedureID");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EprocedureId");

                    b.ToTable("ExperimentalProcedures");

                    b.HasData(
                        new
                        {
                            EprocedureId = "0",
                            Name = "目標設置"
                        },
                        new
                        {
                            EprocedureId = "1",
                            Name = "任務監控"
                        },
                        new
                        {
                            EprocedureId = "2",
                            Name = "自我反思"
                        },
                        new
                        {
                            EprocedureId = "3",
                            Name = "目標設置"
                        },
                        new
                        {
                            EprocedureId = "4",
                            Name = "任務監控"
                        },
                        new
                        {
                            EprocedureId = "5",
                            Name = "團隊反思"
                        },
                        new
                        {
                            EprocedureId = "6",
                            Name = "同儕互評"
                        },
                        new
                        {
                            EprocedureId = "7",
                            Name = "同儕回饋"
                        });
                });

            modelBuilder.Entity("LMSweb.Models.Group", b =>
                {
                    b.Property<int>("Gid")
                        .HasColumnType("int")
                        .HasColumnName("GID");

                    b.Property<string>("Gname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("GName");

                    b.HasKey("Gid");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("LMSweb.Models.Mission", b =>
                {
                    b.Property<string>("Mid")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("MID");

                    b.Property<string>("CourseId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("CourseID");

                    b.Property<string>("CurrentAction")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Mname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("MName");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("Mid");

                    b.HasIndex("CourseId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("LMSweb.Models.Option", b =>
                {
                    b.Property<int>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionID"));

                    b.Property<string>("Ocontent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OContent");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("QuestionID");

                    b.HasKey("OptionID");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            OptionID = 1,
                            Ocontent = "90分以上",
                            QuestionId = "PGS01A"
                        },
                        new
                        {
                            OptionID = 2,
                            Ocontent = "80~90分",
                            QuestionId = "PGS01A"
                        },
                        new
                        {
                            OptionID = 3,
                            Ocontent = "70~80分",
                            QuestionId = "PGS01A"
                        },
                        new
                        {
                            OptionID = 4,
                            Ocontent = "70分以下",
                            QuestionId = "PGS01A"
                        },
                        new
                        {
                            OptionID = 5,
                            Ocontent = "小組成員一起合作 ",
                            QuestionId = "PGS02A"
                        },
                        new
                        {
                            OptionID = 6,
                            Ocontent = "上網找資料",
                            QuestionId = "PGS02A"
                        },
                        new
                        {
                            OptionID = 7,
                            Ocontent = "參考其他小組的解決方案 ",
                            QuestionId = "PGS02A"
                        },
                        new
                        {
                            OptionID = 8,
                            Ocontent = "查看教材",
                            QuestionId = "PGS02A"
                        },
                        new
                        {
                            OptionID = 9,
                            Ocontent = "請教老師或同學",
                            QuestionId = "PGS02A"
                        },
                        new
                        {
                            OptionID = 10,
                            Ocontent = "小組成員一起討論",
                            QuestionId = "PGS03A"
                        },
                        new
                        {
                            OptionID = 11,
                            Ocontent = "合作規劃流程圖",
                            QuestionId = "PGS03A"
                        },
                        new
                        {
                            OptionID = 12,
                            Ocontent = "合作撰寫程式碼",
                            QuestionId = "PGS03A"
                        },
                        new
                        {
                            OptionID = 13,
                            Ocontent = "10分鐘以內",
                            QuestionId = "TM01A"
                        },
                        new
                        {
                            OptionID = 14,
                            Ocontent = "10-15分鐘",
                            QuestionId = "TM01A"
                        },
                        new
                        {
                            OptionID = 15,
                            Ocontent = "15分鐘以上",
                            QuestionId = "TM01A"
                        },
                        new
                        {
                            OptionID = 16,
                            Ocontent = "正確",
                            QuestionId = "CM01A"
                        },
                        new
                        {
                            OptionID = 17,
                            Ocontent = "不完全正確",
                            QuestionId = "CM01A"
                        },
                        new
                        {
                            OptionID = 18,
                            Ocontent = "不正確",
                            QuestionId = "CM01A"
                        },
                        new
                        {
                            OptionID = 19,
                            Ocontent = "有",
                            QuestionId = "TE01A"
                        },
                        new
                        {
                            OptionID = 20,
                            Ocontent = "沒有",
                            QuestionId = "TE01A"
                        },
                        new
                        {
                            OptionID = 21,
                            Ocontent = "90分以上",
                            QuestionId = "SR01A"
                        },
                        new
                        {
                            OptionID = 22,
                            Ocontent = "80~90分",
                            QuestionId = "SR01A"
                        },
                        new
                        {
                            OptionID = 23,
                            Ocontent = "70~80分",
                            QuestionId = "SR01A"
                        },
                        new
                        {
                            OptionID = 24,
                            Ocontent = "60~70分",
                            QuestionId = "SR01A"
                        },
                        new
                        {
                            OptionID = 25,
                            Ocontent = "60分以下",
                            QuestionId = "SR01A"
                        },
                        new
                        {
                            OptionID = 26,
                            Ocontent = "小組成員一起合作 ",
                            QuestionId = "SR02A"
                        },
                        new
                        {
                            OptionID = 27,
                            Ocontent = "上網找資料",
                            QuestionId = "SR02A"
                        },
                        new
                        {
                            OptionID = 28,
                            Ocontent = "參考其他小組的解決方案",
                            QuestionId = "SR02A"
                        },
                        new
                        {
                            OptionID = 29,
                            Ocontent = "查看教材",
                            QuestionId = "SR02A"
                        },
                        new
                        {
                            OptionID = 30,
                            Ocontent = "請教老師或同學",
                            QuestionId = "SR02A"
                        },
                        new
                        {
                            OptionID = 31,
                            Ocontent = "小組成員一起討論",
                            QuestionId = "SR03A"
                        },
                        new
                        {
                            OptionID = 32,
                            Ocontent = "合作規劃流程圖",
                            QuestionId = "SR03A"
                        },
                        new
                        {
                            OptionID = 33,
                            Ocontent = "合作撰寫程式碼",
                            QuestionId = "SR03A"
                        },
                        new
                        {
                            OptionID = 34,
                            Ocontent = "90分以上",
                            QuestionId = "PGS01B"
                        },
                        new
                        {
                            OptionID = 35,
                            Ocontent = "80~90分",
                            QuestionId = "PGS01B"
                        },
                        new
                        {
                            OptionID = 36,
                            Ocontent = "70~80分",
                            QuestionId = "PGS01B"
                        },
                        new
                        {
                            OptionID = 37,
                            Ocontent = "70分以下",
                            QuestionId = "PGS01B"
                        },
                        new
                        {
                            OptionID = 38,
                            Ocontent = "小組成員一起合作 ",
                            QuestionId = "PGS02B"
                        },
                        new
                        {
                            OptionID = 39,
                            Ocontent = "上網找資料",
                            QuestionId = "PGS02B"
                        },
                        new
                        {
                            OptionID = 40,
                            Ocontent = "參考其他小組的解決方案 ",
                            QuestionId = "PGS02B"
                        },
                        new
                        {
                            OptionID = 41,
                            Ocontent = "查看教材",
                            QuestionId = "PGS02B"
                        },
                        new
                        {
                            OptionID = 42,
                            Ocontent = "請教老師或同學",
                            QuestionId = "PGS02B"
                        },
                        new
                        {
                            OptionID = 43,
                            Ocontent = "小組成員一起討論",
                            QuestionId = "PGS03B"
                        },
                        new
                        {
                            OptionID = 44,
                            Ocontent = "合作規劃流程圖",
                            QuestionId = "PGS03B"
                        },
                        new
                        {
                            OptionID = 45,
                            Ocontent = "合作撰寫程式碼",
                            QuestionId = "PGS03B"
                        },
                        new
                        {
                            OptionID = 46,
                            Ocontent = "10分鐘以內",
                            QuestionId = "TM01B"
                        },
                        new
                        {
                            OptionID = 47,
                            Ocontent = "10-15分鐘",
                            QuestionId = "TM01B"
                        },
                        new
                        {
                            OptionID = 48,
                            Ocontent = "15分鐘以上",
                            QuestionId = "TM01B"
                        },
                        new
                        {
                            OptionID = 49,
                            Ocontent = "正確",
                            QuestionId = "CM01B"
                        },
                        new
                        {
                            OptionID = 50,
                            Ocontent = "不完全正確",
                            QuestionId = "CM01B"
                        },
                        new
                        {
                            OptionID = 51,
                            Ocontent = "不正確",
                            QuestionId = "CM01B"
                        },
                        new
                        {
                            OptionID = 52,
                            Ocontent = "有",
                            QuestionId = "TE01B"
                        },
                        new
                        {
                            OptionID = 53,
                            Ocontent = "沒有",
                            QuestionId = "TE01B"
                        },
                        new
                        {
                            OptionID = 54,
                            Ocontent = "90分以上",
                            QuestionId = "TR01B"
                        },
                        new
                        {
                            OptionID = 55,
                            Ocontent = "80~90分",
                            QuestionId = "TR01B"
                        },
                        new
                        {
                            OptionID = 56,
                            Ocontent = "70~80分",
                            QuestionId = "TR01B"
                        },
                        new
                        {
                            OptionID = 57,
                            Ocontent = "60~70分",
                            QuestionId = "TR01B"
                        },
                        new
                        {
                            OptionID = 58,
                            Ocontent = "60分以下",
                            QuestionId = "TR01B"
                        },
                        new
                        {
                            OptionID = 59,
                            Ocontent = "小組成員一起合作 ",
                            QuestionId = "TR02B"
                        },
                        new
                        {
                            OptionID = 60,
                            Ocontent = "上網找資料",
                            QuestionId = "TR02B"
                        },
                        new
                        {
                            OptionID = 61,
                            Ocontent = "參考其他小組的解決方案 ",
                            QuestionId = "TR02B"
                        },
                        new
                        {
                            OptionID = 62,
                            Ocontent = "查看教材",
                            QuestionId = "TR02B"
                        },
                        new
                        {
                            OptionID = 63,
                            Ocontent = "請教老師或同學",
                            QuestionId = "TR02B"
                        },
                        new
                        {
                            OptionID = 64,
                            Ocontent = "小組成員一起討論",
                            QuestionId = "TR03B"
                        },
                        new
                        {
                            OptionID = 65,
                            Ocontent = "合作規劃流程圖",
                            QuestionId = "TR03B"
                        },
                        new
                        {
                            OptionID = 66,
                            Ocontent = "合作撰寫程式碼",
                            QuestionId = "TR03B"
                        },
                        new
                        {
                            OptionID = 67,
                            Ocontent = "3",
                            QuestionId = "PE01"
                        },
                        new
                        {
                            OptionID = 68,
                            Ocontent = "2",
                            QuestionId = "PE01"
                        },
                        new
                        {
                            OptionID = 69,
                            Ocontent = "1",
                            QuestionId = "PE01"
                        },
                        new
                        {
                            OptionID = 70,
                            Ocontent = "3",
                            QuestionId = "PE02"
                        },
                        new
                        {
                            OptionID = 71,
                            Ocontent = "2",
                            QuestionId = "PE02"
                        },
                        new
                        {
                            OptionID = 72,
                            Ocontent = "1",
                            QuestionId = "PE02"
                        },
                        new
                        {
                            OptionID = 73,
                            Ocontent = "3",
                            QuestionId = "PE03"
                        },
                        new
                        {
                            OptionID = 74,
                            Ocontent = "2",
                            QuestionId = "PE03"
                        },
                        new
                        {
                            OptionID = 75,
                            Ocontent = "1",
                            QuestionId = "PE03"
                        },
                        new
                        {
                            OptionID = 76,
                            Ocontent = "非常合理",
                            QuestionId = "PC01"
                        },
                        new
                        {
                            OptionID = 77,
                            Ocontent = "合理",
                            QuestionId = "PC01"
                        },
                        new
                        {
                            OptionID = 78,
                            Ocontent = "不合理",
                            QuestionId = "PC01"
                        },
                        new
                        {
                            OptionID = 79,
                            Ocontent = "非常不合理",
                            QuestionId = "PC01"
                        });
                });

            modelBuilder.Entity("LMSweb.Models.Provided", b =>
                {
                    b.Property<string>("AnswerId")
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(0);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(1);

                    b.Property<string>("MissionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("AnswerId", "UserId");

                    b.HasIndex("MissionId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Provideds");
                });

            modelBuilder.Entity("LMSweb.Models.Question", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("QuestionID");

                    b.Property<string>("CourseId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("CourseID");

                    b.Property<string>("EprocedureId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("EProcedureID");

                    b.Property<string>("Qcontent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QContent");

                    b.Property<string>("Qtype")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QType");

                    b.HasKey("QuestionId");

                    b.HasIndex("CourseId");

                    b.HasIndex("EprocedureId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = "PGS01A",
                            EprocedureId = "0",
                            Qcontent = "我期望這次小組任務可以獲得幾分?",
                            Qtype = "0"
                        },
                        new
                        {
                            QuestionId = "PGS02A",
                            EprocedureId = "0",
                            Qcontent = "為達成目標，我將採用以下哪些學習方法? (可複選)",
                            Qtype = "1"
                        },
                        new
                        {
                            QuestionId = "PGS03A",
                            EprocedureId = "0",
                            Qcontent = "在合作學習中，我會積極參與哪些合作任務? (可複選)",
                            Qtype = "1"
                        },
                        new
                        {
                            QuestionId = "TM01A",
                            EprocedureId = "1",
                            Qcontent = "我認為這次任務需要多長時間完成程式碼的撰寫？",
                            Qtype = "0"
                        },
                        new
                        {
                            QuestionId = "CM01A",
                            EprocedureId = "1",
                            Qcontent = "我認為這份流程圖是正確的嗎？",
                            Qtype = "0"
                        },
                        new
                        {
                            QuestionId = "TE01A",
                            EprocedureId = "2",
                            Qcontent = "我們有沒有依照老師指示完成任務？",
                            Qtype = "0"
                        },
                        new
                        {
                            QuestionId = "SR01A",
                            EprocedureId = "2",
                            Qcontent = "我覺得這次小組任務可以獲得幾分?",
                            Qtype = "0"
                        },
                        new
                        {
                            QuestionId = "SR02A",
                            EprocedureId = "2",
                            Qcontent = "在本次學習任務中，我採用了以下哪些學習方法? (可複選)",
                            Qtype = "1"
                        },
                        new
                        {
                            QuestionId = "SR03A",
                            EprocedureId = "2",
                            Qcontent = "在本次學習任務中，我積極參與了以下哪些合作任務? (可複選)",
                            Qtype = "1"
                        },
                        new
                        {
                            QuestionId = "SR04A",
                            EprocedureId = "2",
                            Qcontent = "依據上述反思，我覺得下個任務可以如何改進?",
                            Qtype = "2"
                        },
                        new
                        {
                            QuestionId = "PGS01B",
                            EprocedureId = "3",
                            Qcontent = "我們期望這次小組任務可以獲得幾分?",
                            Qtype = "0"
                        },
                        new
                        {
                            QuestionId = "PGS02B",
                            EprocedureId = "3",
                            Qcontent = "為達成目標，我們小組將採用以下哪些學習方法? (可複選)",
                            Qtype = "1"
                        },
                        new
                        {
                            QuestionId = "PGS03B",
                            EprocedureId = "3",
                            Qcontent = "在合作學習中，我們小組會積極參與哪些合作任務? (可複選)",
                            Qtype = "1"
                        },
                        new
                        {
                            QuestionId = "TM01B",
                            EprocedureId = "4",
                            Qcontent = "我們認為這次任務需要多長時間完成程式碼的撰寫？",
                            Qtype = "0"
                        },
                        new
                        {
                            QuestionId = "CM01B",
                            EprocedureId = "4",
                            Qcontent = "我們認為這份流程圖是正確的嗎？",
                            Qtype = "0"
                        },
                        new
                        {
                            QuestionId = "TE01B",
                            EprocedureId = "5",
                            Qcontent = "我們有沒有依照老師指示完成任務？",
                            Qtype = "0"
                        },
                        new
                        {
                            QuestionId = "SR01B",
                            EprocedureId = "5",
                            Qcontent = "我們覺得這次小組任務可以獲得幾分?",
                            Qtype = "0"
                        },
                        new
                        {
                            QuestionId = "SR02B",
                            EprocedureId = "5",
                            Qcontent = "在本次學習任務中，我們小組採用了以下哪些學習方法? (可複選)",
                            Qtype = "1"
                        },
                        new
                        {
                            QuestionId = "SR03B",
                            EprocedureId = "5",
                            Qcontent = "在本次學習任務中，我們小組積極參與了以下哪些合作任務? (可複選)",
                            Qtype = "1"
                        },
                        new
                        {
                            QuestionId = "SR04B",
                            EprocedureId = "5",
                            Qcontent = "依據上述反思，我們小組覺得下個任務可以如何改進?",
                            Qtype = "2"
                        },
                        new
                        {
                            QuestionId = "TR01B",
                            EprocedureId = "2",
                            Qcontent = "我們期望我們小組在這次任務可以得到幾分？",
                            Qtype = "0"
                        },
                        new
                        {
                            QuestionId = "TR02B",
                            EprocedureId = "2",
                            Qcontent = "為達成目標，我們將採用以下那些學習方法？",
                            Qtype = "1"
                        },
                        new
                        {
                            QuestionId = "TR03B",
                            EprocedureId = "2",
                            Qcontent = "在合作學習中，我們希望能積極參與以下合作任務？",
                            Qtype = "1"
                        },
                        new
                        {
                            QuestionId = "TR04B",
                            EprocedureId = "2",
                            Qcontent = "依據上述反思，我們覺得下個任務可以如何改進？",
                            Qtype = "2"
                        },
                        new
                        {
                            QuestionId = "PE01",
                            EprocedureId = "6",
                            Qcontent = "我們覺得這一組的邏輯性可以獲得幾分?",
                            Qtype = "0"
                        },
                        new
                        {
                            QuestionId = "PE02",
                            EprocedureId = "6",
                            Qcontent = "我們覺得這一組的正確性可以獲得幾分?",
                            Qtype = "0"
                        },
                        new
                        {
                            QuestionId = "PE03",
                            EprocedureId = "6",
                            Qcontent = "我們覺得這一組的可讀性可以獲得幾分?",
                            Qtype = "0"
                        },
                        new
                        {
                            QuestionId = "PC01",
                            EprocedureId = "7",
                            Qcontent = "該組評價合理嗎?",
                            Qtype = "0"
                        });
                });

            modelBuilder.Entity("LMSweb.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("StudentID");

                    b.Property<string>("CourseId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("CourseID");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GroupID");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("bit")
                        .HasColumnName("isLeader");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId")
                        .HasName("PK_Student");

                    b.HasIndex("CourseId");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = "S001",
                            IsLeader = false,
                            StudentName = "林世楷"
                        },
                        new
                        {
                            StudentId = "S002",
                            IsLeader = false,
                            StudentName = "李國禎"
                        },
                        new
                        {
                            StudentId = "S003",
                            IsLeader = false,
                            StudentName = "許盈琪"
                        },
                        new
                        {
                            StudentId = "S004",
                            IsLeader = false,
                            StudentName = "Kevin"
                        },
                        new
                        {
                            StudentId = "S005",
                            IsLeader = false,
                            StudentName = "Vivian"
                        },
                        new
                        {
                            StudentId = "S006",
                            IsLeader = false,
                            StudentName = "Amy"
                        });
                });

            modelBuilder.Entity("LMSweb.Models.Teacher", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("TeacherID");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = "T001",
                            TeacherName = "Lee"
                        },
                        new
                        {
                            TeacherId = "T002",
                            TeacherName = "曾老師"
                        },
                        new
                        {
                            TeacherId = "T003",
                            TeacherName = "李偉老師"
                        },
                        new
                        {
                            TeacherId = "T004",
                            TeacherName = "焰超老師"
                        });
                });

            modelBuilder.Entity("LMSweb.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ID");

                    b.Property<string>("Gender")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Upassword")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("UPassword");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "S001",
                            Gender = "男",
                            Name = "林世楷",
                            RoleName = "Student",
                            Upassword = "c5e0e70cb9001fc326a9d5b3c39c1d3b48919bf3adacc633729bfff7c27f1d26"
                        },
                        new
                        {
                            Id = "S002",
                            Gender = "男",
                            Name = "李國禎",
                            RoleName = "Student",
                            Upassword = "c842f8af9e82946217a5f35c046c0470ce855b145a093448295d758810c68303"
                        },
                        new
                        {
                            Id = "S003",
                            Gender = "女",
                            Name = "許盈琪",
                            RoleName = "Student",
                            Upassword = "f598aee2eda0ebd461a60eb24ecc6378674be0d06a591ef8f25b201e4f619e48"
                        },
                        new
                        {
                            Id = "S004",
                            Gender = "男",
                            Name = "Kevin",
                            RoleName = "Student",
                            Upassword = "db3ea858db39f2f6eafd7ad39f7798428d9e6244a430919f84c7dc8b905081ad"
                        },
                        new
                        {
                            Id = "S005",
                            Gender = "女",
                            Name = "Vivian",
                            RoleName = "Student",
                            Upassword = "09fd191dc08a0375f4f10fd8ce970d8193a0b475bb3d75db4b8221e8f0d74979"
                        },
                        new
                        {
                            Id = "S006",
                            Gender = "女",
                            Name = "Amy",
                            RoleName = "Student",
                            Upassword = "19a85017e5a5057f9cb3104e7afde89aea6c4d74f544ba5eaeaab256bcf937af"
                        },
                        new
                        {
                            Id = "T001",
                            Name = "Lee",
                            RoleName = "Teacher",
                            Upassword = "15152d459354c17470fbeba5c03aa9b0790b237b04f190aba04b2a3d1afe64bf"
                        },
                        new
                        {
                            Id = "T002",
                            Name = "曾老師",
                            RoleName = "Teacher",
                            Upassword = "9ba7d0652682e1fe75b90bd1ea8a1a69e679a0039c80fc9c85e10e2ff7ddc793"
                        },
                        new
                        {
                            Id = "T003",
                            Name = "李偉老師",
                            RoleName = "Teacher",
                            Upassword = "963606fbc3791a6c3053264f977ce910821a69680e5e41de99e6b3f04d7d0471"
                        },
                        new
                        {
                            Id = "T004",
                            Name = "焰超老師",
                            RoleName = "Teacher",
                            Upassword = "efcc4b59f003f0a56d6869d748cf3d31c3a4d36a6a8b9bbe60cb2171294b896c"
                        });
                });

            modelBuilder.Entity("LMSweb.Models.Answer", b =>
                {
                    b.HasOne("LMSweb.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_Answers_Questions");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("LMSweb.Models.Course", b =>
                {
                    b.HasOne("LMSweb.Models.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Courses_Teachers");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LMSweb.Models.Execution", b =>
                {
                    b.HasOne("LMSweb.Models.Group", "Group")
                        .WithMany("Executions")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_Executions_Groups");

                    b.HasOne("LMSweb.Models.Mission", "Mission")
                        .WithMany("Executions")
                        .HasForeignKey("MissionId")
                        .IsRequired()
                        .HasConstraintName("FK_Executions_Missions");

                    b.Navigation("Group");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("LMSweb.Models.Mission", b =>
                {
                    b.HasOne("LMSweb.Models.Course", "Course")
                        .WithMany("Missions")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK_Missions_Courses");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LMSweb.Models.Option", b =>
                {
                    b.HasOne("LMSweb.Models.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_Options_Questions");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("LMSweb.Models.Provided", b =>
                {
                    b.HasOne("LMSweb.Models.Answer", "Answer")
                        .WithMany("Provideds")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMSweb.Models.Mission", "Mission")
                        .WithOne("Provided")
                        .HasForeignKey("LMSweb.Models.Provided", "MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMSweb.Models.User", "User")
                        .WithOne("Provided")
                        .HasForeignKey("LMSweb.Models.Provided", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Mission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMSweb.Models.Question", b =>
                {
                    b.HasOne("LMSweb.Models.Course", "Course")
                        .WithMany("Questions")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK_Questions_Courses");

                    b.HasOne("LMSweb.Models.ExperimentalProcedure", "Eprocedure")
                        .WithMany("Questions")
                        .HasForeignKey("EprocedureId")
                        .IsRequired()
                        .HasConstraintName("FK_Questions_ExperimentalProcedures");

                    b.Navigation("Course");

                    b.Navigation("Eprocedure");
                });

            modelBuilder.Entity("LMSweb.Models.Student", b =>
                {
                    b.HasOne("LMSweb.Models.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK_Student_Student");

                    b.HasOne("LMSweb.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK_Students_Groups");

                    b.HasOne("LMSweb.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("LMSweb.Models.Student", "StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Students_Users");

                    b.Navigation("Course");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMSweb.Models.Teacher", b =>
                {
                    b.HasOne("LMSweb.Models.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("LMSweb.Models.Teacher", "TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_Teachers_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMSweb.Models.Answer", b =>
                {
                    b.Navigation("Provideds");
                });

            modelBuilder.Entity("LMSweb.Models.Course", b =>
                {
                    b.Navigation("Missions");

                    b.Navigation("Questions");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("LMSweb.Models.ExperimentalProcedure", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LMSweb.Models.Group", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("LMSweb.Models.Mission", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("Provided");
                });

            modelBuilder.Entity("LMSweb.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("LMSweb.Models.Teacher", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("LMSweb.Models.User", b =>
                {
                    b.Navigation("Provided");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
